module.exports = {
  SET_TIMER: 'SET_TIMER',
  START_TIMER: 'START_TIMER',
  STOP_TIMER: 'STOP_TIMER',
  TIMER_STOPPED: 'TIMER_STOPPED',

  START_POMODORO: 'START_POMODORO',
  RESET_POMODORO: 'RESET_POMODORO'
};
